language: node_js
node_js:
  - 12

before_install:
  - echo "Testing Docker Hub credentials"

script:
  - npm test

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; else npm run deply:dry fi